# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main", "IncludeMetrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: basic metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: basic-metrics.svg
          user: bstordrup
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, organization-member, collaborator
          #config_timezone: Europe/Copenhagen

      - name: activity metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: activity-metrics.svg
          base: ""
          config_timezone: Europe/Copenhagen
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 500
          plugin_activity_visibility: public

      - name: habits metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habit-metrics.svg
          base: ""
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 500
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

      - name: lines metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: line-metrics.svg
          base: ""
          config_timezone: Europe/Copenhagen
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: repositories, history
          # plugin_lines_skipped: | 
          #   @use.patterns
          #   bd*, top*
          repositories_skipped: |
            @use.patterns

            bstordrup/bd*
            bstordrup/top*

      - name: iso-calendar metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: iso-calendar-metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - name: languages metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages-metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          #plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          #plugin_languages_analysis_timeout: 15
          #plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          #plugin_languages_recent_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          #plugin_languages_threshold: 2%

      - name: notable metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: notable-metrics.svg
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull-request
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes


      #- uses: lowlighter/metrics@latest
      #  with:
      #    # Your GitHub token
      #    # The following scopes are required:
      #    #  - public_access (default scope)
      #    # The following additional scopes may be required:
      #    #  - read:org      (for organization related metrics)
      #    #  - read:user     (for user related data)
      #    #  - read:packages (for some packages related data)
      #    #  - repo          (optional, if you want to include private repositories)
      #    token: ${{ secrets.METRICS_TOKEN }}
      #    #filename: basicmetrics.svg
      #
      #    # Options
      #    user: Bstordrup
      #    template: classic
      #    #base: header, activity, community, repositories, metadata
      #    config_timezone: Europe/Copenhagen
      #    #plugin_achievements: yes
      #    #plugin_achievements_display: detailed
      #    #plugin_achievements_secrets: yes
      #    #plugin_achievements_threshold: C
      #    plugin_calendar: yes
      #    plugin_calendar_limit: 1
      #    plugin_stars: yes
      #    plugin_stars_limit: 5
